/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Entity.Tickets;
import Tools.ConnectionBDD;
import Tools.FonctionsMetier;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class frmUser extends javax.swing.JFrame {

    /**
     * Creates new form frmUser
     */
    public frmUser(String login) {
        initComponents();
        this.login = login;
    }
    String login;
    ConnectionBDD bdd;
    FonctionsMetier fm;
    Vector v;
    DefaultTableModel dtmTicketUser;
    int idUser;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTicketUser = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cbxEtatTicket = new javax.swing.JComboBox<>();
        btnModifTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USER");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Liste des Tickets");

        tblTicketUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nom", "Date", "Etat"
            }
        ));
        jScrollPane1.setViewportView(tblTicketUser);

        jLabel3.setText("Les Etats");
        jLabel3.setToolTipText("");

        cbxEtatTicket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bloquant", "Majeur", "Mineur", "Terminé" }));

        btnModifTicket.setText("Modifier l'état du ticket");
        btnModifTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifTicketMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbxEtatTicket, 0, 197, Short.MAX_VALUE))
                            .addComponent(btnModifTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbxEtatTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addComponent(btnModifTicket)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        bdd = new ConnectionBDD();
        fm = new FonctionsMetier();
        dtmTicketUser = (DefaultTableModel) tblTicketUser.getModel();
        idUser = fm.GetIdUser(this.login);
        for (Tickets t : fm.GetAllTicket(idUser))
        {
            v = new Vector();
            v.add(t.getIdTicket());
            v.add(t.getNomTicket());
            v.add(t.getDateTicket());
            v.add(fm.GetEtatTicket(t.getNumEtat()));
            dtmTicketUser.addRow(v);
        }
        tblTicketUser.setModel(dtmTicketUser);
        
    }//GEN-LAST:event_formWindowOpened

    private void btnModifTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifTicketMouseClicked
        // TODO add your handling code here:
        int selectedTicket = tblTicketUser.getSelectedRow();
        if (selectedTicket < 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Vous n'avez pas selectionner de ticket", "Erreur Non Selection", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String newEtatTicket = cbxEtatTicket.getSelectedItem().toString();
        
            fm.ModifierEtatTicketUser(newEtatTicket, Integer.parseInt(tblTicketUser.getValueAt(tblTicketUser.getSelectedRow(), 0).toString()));
        }
        while(tblTicketUser.getRowCount() > 0)
        {
            dtmTicketUser.removeRow(0);
        }
        for (Tickets t : fm.GetAllTicket(idUser))
        {
            v = new Vector();
            v.add(t.getIdTicket());
            v.add(t.getNomTicket());
            v.add(t.getDateTicket());
            v.add(fm.GetEtatTicket(t.getNumEtat()));
            dtmTicketUser.addRow(v);
        }
        tblTicketUser.setModel(dtmTicketUser);
    }//GEN-LAST:event_btnModifTicketMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /**java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUser(login).setVisible(true);
            }
        });**/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModifTicket;
    private javax.swing.JComboBox<String> cbxEtatTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTicketUser;
    // End of variables declaration//GEN-END:variables
}
